// The ocean's controls, for the in-dive help and the menu's Controls page.
// ('#' rows are section headings.)

export const OCEAN_KEY_SECTIONS: [string, string][][] = [
  [
    ['#', 'DRIVING'],
    ['W / S', 'Thrust ahead / astern'],
    ['A / D', 'Turn left / right'],
    ['← / →', 'Side thrusters'],
    ['R / F', 'Vertical thrusters up / down'],
    ['Z', 'Flood the ballast tanks (heavier: dive)'],
    ['X', 'Blow the tanks (lighter: rise)'],
    ['B', 'Emergency blow: straight to the surface'],
    ['T', 'Hold this depth'],
    ['G', 'Hold this position'],
    [', / .', 'Time warp down / up: 1× to 100× (or drag the slider); open water only, held back near the bottom, the sites and the harbor'],
  ],
  [
    ['#', 'SURVEY'],
    ['Q', 'Quiet Survey: thrusters quiet, hydrophones listen'],
    ['P', 'Sonar ping: one turn of the scanning head (masks faint sounds for 6 s)'],
    ['N', 'Scanning sonar on / off: the head keeps turning (the hydrophones are masked)'],
    ['O', 'Sonar overlay on / off'],
    ['L', 'Lamps on / off'],
    ['K', 'Floodlights on / off: light all round the boat'],
    ['E', 'Use: scan, recover with the arm, dock'],
  ],
  [
    ['#', 'MANIPULATOR ARM'],
    ['V', 'Arm out (the boat holds its place) / stow it'],
    ['W / S', 'Jaw ahead / back'],
    ['A / D', 'Jaw left / right'],
    ['R / F', 'Jaw up / down'],
    ['E', 'Grip what is in the jaw / let go'],
    ['V', 'Stow: what it holds goes in the sample basket'],
  ],
  [
    ['#', 'VIEW'],
    ['C', 'Camera: chase / pilot\'s dome'],
    ['Drag', 'Look around · wheel zooms'],
    ['M', 'Chart and Echo Atlas'],
    ['H or ?', 'This help'],
    ['Esc', 'Pause'],
  ],
  [
    ['#', 'GAMEPAD'],
    ['Left stick', 'Thrust ahead / astern, turn'],
    ['RT / LT', 'Vertical thrusters up / down'],
    ['RB / LB', 'Side thrusters'],
    ['D-pad ▲ / ▼', 'Blow / flood the tanks · hold ▲ 2 s: emergency blow'],
    ['D-pad ◀ / ▶', 'Hold depth / hold position'],
    ['A · B · X · Y', 'Use · ping · Quiet Survey · lamps'],
    ['Hold A · B · Y', 'Arm out / stow · scanning sonar · floodlights'],
    ['Right stick', 'Look around · press: sonar overlay'],
    ['Left stick press', 'Camera'],
    ['View · Menu', 'Chart · pause'],
  ],
  [
    ['#', 'TOUCH'],
    ['Stick', 'Thrust ahead / astern, turn'],
    ['Buttons', 'Up / down, flood / blow, side thrust, listen, ping, use, lamps, holds, transit time, arm, scanning sonar, floodlights'],
    ['Arm out', 'The stick and up / down move the jaw; USE grips'],
    ['Emergency blow', 'Hold the button 2 s'],
    ['Drag · pinch', 'Look around · zoom'],
  ],
];
