// The facts shown along the bottom of the loading screen, one at a time: a
// hundred each for the air and space programs, thirty for the ocean.

export const AIR_FACTS: string[] = [
  'The SR-71 Blackbird still holds the speed record for a crewed air-breathing jet: 2,193 mph, set in 1976.',
  "The SR-71's titanium skin got so hot in flight that the whole airframe grew several inches longer.",
  'On the ground the SR-71 leaked fuel: its panels only sealed once flight heated them and they expanded.',
  "The F-22's engine nozzles can vector their thrust up or down by 20 degrees.",
  "Pugachev's Cobra, the Su-27's famous nose-up stop, was first shown publicly at the 1989 Paris Air Show.",
  'In 1963 Joe Walker flew the X-15 to 354,200 ft: above the 100 km line that marks the edge of space.',
  'Pete Knight flew the X-15 to Mach 6.7 in 1967, still the fastest flight ever made in a crewed, winged aircraft.',
  'Chuck Yeager first broke the sound barrier on 14 October 1947, in the rocket-powered Bell X-1.',
  "Yeager named his X-1 \"Glamorous Glennis\" after his wife.",
  'At sea level on a standard day, the speed of sound is about 761 mph (1,225 km/h).',
  'Sound travels slower in cold air, so Mach 1 at 36,000 ft is only about 660 mph.',
  "A vapour cone is moisture condensing in the low pressure around a fast jet. It isn't the sonic boom itself.",
  'G-suits squeeze the legs and belly so blood stays in the brain during hard turns.',
  'Without a G-suit or a straining manoeuvre, most people black out at around 5 g.',
  'The F-16 was the first production fighter designed to sustain 9 g.',
  "The F-16's bubble canopy has no frame in front of the pilot, for an unbroken view.",
  'The F-15 is credited with more than 100 air-to-air victories without a single loss in air combat.',
  'In 1983 an Israeli F-15 landed safely after losing most of its right wing in a mid-air collision.',
  'The "F/A" in F/A-18 stands for Fighter/Attack: one jet for both jobs.',
  'The Eurofighter Typhoon is built by a consortium from the UK, Germany, Italy and Spain.',
  'The Typhoon can supercruise: fly faster than sound without using its afterburners.',
  'The F-22 can supercruise at around Mach 1.5.',
  'The F-35 comes in three versions: A for runways, B for short take-off and vertical landing, C for carriers.',
  'To hover, the F-35B uses a shaft-driven lift fan behind the cockpit and swivels its main nozzle downward.',
  'Rafale is French for "a gust of wind".',
  'The Rafale flies with both the French Air and Space Force and the French Navy, from the carrier Charles de Gaulle.',
  'The Gripen was designed to fly from ordinary roads, and a small ground crew can refuel and rearm it in about ten minutes.',
  "The Gripen E's engine is the General Electric F414, from the same family as the Super Hornet's.",
  'The MiG-31 is one of the fastest combat jets ever built, with a top speed of about Mach 2.83.',
  'The MiG-31 grew out of the MiG-25, which was built mostly from nickel steel rather than aluminium.',
  'A MiG-25 could reach Mach 3.2, but at that speed it risked wrecking its own engines.',
  "The Su-57, Russia's first stealth fighter, made its first flight in 2010.",
  "The Su-35S's engine nozzles can vector thrust in three dimensions.",
  'An afterburner sprays fuel into the exhaust behind the turbine: a big jump in thrust, at a huge cost in fuel.',
  'In full afterburner a fighter can burn fuel several times faster than at cruise.',
  '"Bingo fuel" means only enough fuel is left to get home safely.',
  '"Joker fuel" is a planned fuel state above bingo: the cue to start thinking about going home.',
  '"Fox Two" is the call for firing a heat-seeking missile; "Fox Three" is for an active radar missile.',
  '"Splash" means the target has been destroyed.',
  '"Tally" means a pilot can see the target; "no joy" means they can\'t.',
  '"Angels 20" means 20,000 ft.',
  '"Buster" means fly at full military power.',
  'The AIM-9 Sidewinder is named after a rattlesnake that hunts by sensing the heat of its prey.',
  'The first air-to-air kill with a Sidewinder came in 1958, over the Taiwan Strait.',
  'The AIM-120 AMRAAM is "fire and forget": near the end its own radar takes over the hunt.',
  'The Meteor missile is powered by a ramjet, so it can keep thrusting all the way to its target.',
  'Flares decoy heat-seeking missiles; chaff, clouds of thin metal strips, confuses radar.',
  'A carrier jet lands by catching one of the arresting wires across the deck with its tailhook.',
  'On a carrier, pilots go to full power the moment they touch down, in case the hook misses the wires.',
  'A carrier catapult flings a jet from a standstill to around 150 knots in about two seconds.',
  'On a carrier with four arresting wires, pilots aim to catch the third.',
  'The "meatball" is the light on a carrier that shows a pilot whether they are high or low on the glide path.',
  'The US Air Force refuels through a rigid boom; the US Navy and many other forces use a hose and drogue.',
  'The KC-46 Pegasus tanker is based on the Boeing 767 airliner.',
  'The wingtip vortices behind a big aircraft can linger in calm air for minutes.',
  'In a knife-edge pass the jet is banked 90 degrees, held up by its fuselage and engine thrust.',
  'The US Navy Blue Angels fly F/A-18 Super Hornets; the US Air Force Thunderbirds fly F-16s.',
  "Britain's Red Arrows fly BAE Hawks.",
  "In the Blue Angels' Diamond formation, the jets fly just 18 inches (45 cm) apart.",
  'Stealth aircraft cut their radar return with carefully angled shapes and radar-absorbent materials.',
  "The F-117's faceted shape came from 1970s computers that could only work out radar returns from flat panels.",
  'Stealth fighters carry their weapons in internal bays, which open only for an instant to fire.',
  "The F-22's radar cross-section is often compared to that of a marble.",
  'Modern ejection seats work even at zero altitude and zero speed, which is called "zero-zero".',
  'Martin-Baker ejection seats have saved more than 7,000 lives.',
  'HUD stands for head-up display: flight data shown in front of the pilot, so they can keep looking outside.',
  'With a helmet-mounted sight, a pilot can aim a missile just by looking at the target.',
  "Cameras around the F-35 let the pilot's helmet show the view through the floor of the jet.",
  'To recover from a stall, a pilot lowers the nose so the wing can regain airspeed.',
  "Angle of attack is the angle between the wing and the oncoming air, not the angle of the nose to the horizon.",
  "The leading-edge extensions beside the F/A-18's cockpit make vortices that keep the wing flying at high angles of attack.",
  'A sonic boom follows a supersonic jet along its whole path, not just at the moment it passes Mach 1.',
  'Concorde cruised at Mach 2.04 and crossed the Atlantic in about three and a half hours.',
  'Concorde carried passengers from 1976 to 2003.',
  'The jet engine was invented separately by Frank Whittle in Britain and Hans von Ohain in Germany.',
  'The first jet aircraft to fly was the Heinkel He 178, in 1939.',
  'The Messerschmitt Me 262 was the first jet fighter to go into service.',
  'Military jet fuels such as JP-8 are kerosene-based.',
  'The F-15EX Eagle II can carry up to twelve air-to-air missiles.',
  'The F-15EX has fully digital fly-by-wire controls, where earlier Eagles had mechanical linkages.',
  'Aviation runs on "Zulu" time (UTC), so everyone shares one clock.',
  'A nautical mile is 1,852 metres: one minute of latitude.',
  'One knot is one nautical mile per hour.',
  'A runway number is its magnetic heading divided by ten: runway 27 points roughly west, 270 degrees.',
  '"Mayday" comes from the French "m\'aider": "help me".',
  'In a go-around, the pilot abandons a landing and climbs away to try again.',
  'An altimeter measures air pressure, so pilots set it to the local pressure to read their height correctly.',
  'QNH is the altimeter setting that makes it read height above sea level.',
  'Around Mach 0.8, shock waves can already form on the wing, where the air speeds up over the curve.',
  'The area rule, a "Coke bottle" pinch in the fuselage, cuts drag near the speed of sound.',
  'Swept wings delay the sharp rise in drag as a jet nears the speed of sound.',
  'Delta wings like those on the Typhoon and Rafale are strong, hold lots of fuel and suit high speed.',
  'Canards, small wings near the nose, help the Typhoon, Rafale and Gripen pitch quickly.',
  'Most modern fighters are deliberately unstable: their computers keep them flying straight, and that makes them more agile.',
  'The U-2 flies above 70,000 ft, where its pilots wear pressure suits much like astronauts.',
  'When a U-2 lands, a chase car races behind it calling out the height, because the pilot can see so little.',
  'The B-2 Spirit is a pure flying wing, with no tail at all.',
  "The A-10 was designed around its GAU-8 cannon, which is about as long as a car.",
  'Airshow photographers pan with the jet at a slow shutter speed: the background blurs while the jet stays sharp.',
];

export const SPACE_FACTS: string[] = [
  "The Saturn V produced about 7.5 million pounds of thrust at liftoff.",
  'The Saturn V stood 110.6 m (363 ft) tall, taller than the Statue of Liberty on its pedestal.',
  'The F-1 is still the most powerful single-chamber liquid-fuelled rocket engine ever flown.',
  'Apollo 11 landed on the Moon on 20 July 1969.',
  'Neil Armstrong and Buzz Aldrin spent about two and a half hours walking on the Moon.',
  'While Armstrong and Aldrin were on the surface, Michael Collins orbited alone in the command module Columbia.',
  'Twelve people have walked on the Moon, all between 1969 and 1972.',
  'Gene Cernan of Apollo 17 was the last person to walk on the Moon, in December 1972.',
  'The Apollo Guidance Computer had 2,048 words of erasable memory, about 4 KB.',
  'Staying in low Earth orbit takes about 7.8 km/s: roughly 28,000 km/h.',
  'The ISS goes round the Earth about every 90 minutes, so its crew see around 16 sunrises a day.',
  'People have lived on the ISS continuously since November 2000.',
  'With its solar arrays, the ISS is about as big as an American football field.',
  "Escaping Earth's gravity from the surface takes about 11.2 km/s.",
  'The Kármán line, 100 km up, is the most widely used boundary of space.',
  'Astronauts float because they are falling around the Earth all the time, not because there is no gravity.',
  "At the ISS's height, gravity is still about 90% as strong as on the ground.",
  "Gravity on Mars is about 38% of Earth's.",
  'A day on Mars, called a sol, lasts about 24 hours and 39 minutes.',
  'Olympus Mons on Mars rises about 22 km, nearly three times the height of Everest.',
  'Valles Marineris, the great canyon of Mars, is more than 4,000 km long.',
  'Mars is red because of iron oxide (rust) in its dust.',
  'Sunsets on Mars look blue: the fine dust scatters blue light forward, toward the Sun.',
  "The Martian air is about 95% carbon dioxide and less than 1% as dense as Earth's.",
  'Perseverance landed in Jezero Crater on 18 February 2021.',
  'Jezero Crater once held a lake, and Perseverance is exploring the old river delta that fed it.',
  'Perseverance seals rock cores in tubes so they could one day be brought back to Earth.',
  'On 19 April 2021, Ingenuity became the first aircraft to make a powered flight on another planet.',
  'Ingenuity was meant to make five flights. It made 72.',
  "Ingenuity's rotors spun at about 2,500 rpm to grip Mars's thin air.",
  'Curiosity landed in Gale Crater in August 2012 and has been climbing Mount Sharp since 2014.',
  'Curiosity and Perseverance run on the heat of decaying plutonium-238, not on solar panels.',
  'A "sky crane", a rocket-powered descent stage, lowered Curiosity and Perseverance to the ground on cables.',
  'Landing on Mars is nicknamed "seven minutes of terror".',
  'Radio signals take between about 3 and 22 minutes to cross between Earth and Mars.',
  "Because of that delay, rover drivers plan each day's drive in advance.",
  'On flat ground, Perseverance tops out at about 4.2 cm per second.',
  'Perseverance carries microphones and has recorded the wind blowing on Mars.',
  "MOXIE, an experiment on Perseverance, made oxygen out of Mars's carbon dioxide air.",
  "Phobos is spiralling slowly toward Mars and will crash or break apart in tens of millions of years.",
  'Mars has two small moons: Phobos and Deimos.',
  'Falcon 9 first stages fly themselves back to land, on a drone ship or near the launch site.',
  'The first Falcon 9 booster landing came in December 2015.',
  "Falcon Heavy's first flight, in 2018, sent a Tesla Roadster out past the orbit of Mars.",
  "Falcon Heavy's two side boosters touch down side by side, almost at the same moment.",
  'In 2022, SLS launched Artemis I, sending an uncrewed Orion around the Moon and back.',
  "Orion's heat shield faces about 2,800 °C coming home from the Moon.",
  'Starship is the largest and most powerful rocket ever flown.',
  'Super Heavy, the first stage of Starship, has 33 Raptor engines.',
  'SpaceX catches returning Super Heavy boosters with two arms on the launch tower, nicknamed the "chopsticks".',
  'Raptor engines burn liquid methane and liquid oxygen.',
  'One day, methane could be made on Mars from water ice and carbon dioxide.',
  'Crew Dragon docks with the ISS automatically, though the crew can take over.',
  'Crew Dragon first carried astronauts to the ISS in 2020, on the Demo-2 mission.',
  'Rocket engines work in a vacuum because they carry their own oxidiser.',
  'Specific impulse measures how efficiently a rocket engine uses its propellant.',
  'Liquid hydrogen is very efficient fuel but very light, so hydrogen rockets need huge tanks.',
  "SLS's core stage uses four RS-25 engines, the same type that flew on the Space Shuttle.",
  'Max Q is the moment when the air pushes hardest on a climbing rocket.',
  "Rockets launch eastward to borrow Earth's spin: about 465 m/s at the equator.",
  "Launch sites near the equator get a bigger boost from Earth's rotation.",
  'Staging drops empty tanks and engines, so the rest of the rocket has less to carry.',
  'In a gravity turn, gravity gradually tips a climbing rocket over, saving fuel and strain.',
  'A Hohmann transfer is the most fuel-efficient way to move between two circular orbits.',
  'Launch windows to Mars open about every 26 months.',
  'With today\'s rockets, a one-way trip to Mars takes about seven months.',
  "Aerobraking slows a spacecraft by dipping it into a planet's upper atmosphere, with no fuel at all.",
  'Geostationary orbit is about 35,786 km above the equator.',
  'The Moon is drifting away from the Earth by about 3.8 cm a year.',
  'The Moon always shows us the same face because it is tidally locked.',
  'The far side of the Moon is not dark: it gets just as much sunlight as the near side.',
  'Sunlight takes about 8 minutes 20 seconds to reach the Earth.',
  'More than 1,300 Earths could fit inside Jupiter.',
  'Saturn is less dense than water.',
  'A day on Venus is longer than its year.',
  'Under its thick carbon dioxide atmosphere, the surface of Venus is about 465 °C.',
  'Mercury has almost no atmosphere, so its temperature swings from about 430 °C to −180 °C.',
  "Jupiter's moon Europa has a salty ocean under its shell of ice.",
  "Saturn's moon Titan has lakes of liquid methane and ethane.",
  "Titan's atmosphere is thicker than Earth's.",
  'Neptune has the fastest winds in the Solar System, over 2,000 km/h.',
  'Uranus rolls around the Sun on its side, tilted about 98 degrees.',
  'Voyager 1 is the most distant human-made object, more than 24 billion km away.',
  'Both Voyagers carry golden records of the sounds and pictures of Earth.',
  "The Sun holds about 99.8% of all the mass in the Solar System.",
  'Footprints on the Moon could last for millions of years: there is no wind to wear them away.',
  'Moon dust is sharp and clingy because wind and water have never worn it smooth.',
  'A spacewalk from the ISS usually lasts six to seven hours.',
  'In microgravity, astronauts can grow up to about 3% taller as their spines stretch out.',
  'The ISS recycles about 98% of its water, including from sweat and urine.',
  'The Hubble Space Telescope was launched in 1990, and Shuttle crews serviced it five times.',
  'The James Webb Space Telescope orbits near the L2 point, about 1.5 million km from Earth.',
  'Re-entry heat comes mostly from air compressed in front of the spacecraft, not from friction.',
  'Yuri Gagarin became the first person in space on 12 April 1961.',
  'In 1963, Valentina Tereshkova became the first woman in space.',
  'Sputnik 1, launched in 1957, was the first artificial satellite.',
  'Alan Shepard hit golf balls on the Moon during Apollo 14.',
  'Astronauts drove the Lunar Roving Vehicle on Apollo 15, 16 and 17.',
  "After an oxygen tank exploded, Apollo 13's crew came home safely in 1970, using their lunar module as a lifeboat.",
  'At the top time warp of 1,000,000×, a whole month goes by in under three seconds.',
];

export const OCEAN_FACTS: string[] = [
  'Sound travels through seawater at about 1,500 m/s, more than four times faster than through air.',
  'Seawater absorbs red light first: ten metres down most of it is gone, which is why photographs without a lamp look blue-green.',
  'Water absorbs blue light least, which is why deep water looks blue.',
  'In the clearest ocean water, enough sunlight for plants reaches about 200 m down. Below that is the twilight zone.',
  'Below about 1,000 m no sunlight is left at all: the midnight zone.',
  'Every 10 m of seawater adds about one atmosphere of pressure.',
  "Seen from under a calm surface, the whole sky is squeezed into a circle about 97 degrees across: Snell's window.",
  "Outside Snell's window the underside of the surface is a mirror: light from below is totally reflected.",
  'The dancing net of light on a shallow sea bed is sunlight focused by the curved surfaces of the waves.',
  'The underwater locator beacons on flight recorders send a 37.5 kHz pulse about once a second.',
  'Seawater absorbs high-pitched sound far more than low: about 1 dB per kilometre at 10 kHz, about 10 dB at 37.5 kHz.',
  "Thorp's formula, published in 1967, is still a good estimate of how seawater absorbs sound at sonar frequencies.",
  "Knudsen's curves, from 1948, describe how the background noise of the sea rises with the wind and the waves.",
  'Passive sonar only listens. Active sonar sends out a pulse and listens for echoes, and tells everyone where it was sent from.',
  'Two bearings on the same sound, taken from two different places, cross where the sound comes from.',
  'A submersible floods its ballast tanks to grow heavier and dive, and blows compressed air into them to rise.',
  'A boat that weighs exactly as much as the water it displaces neither rises nor sinks: it is neutrally buoyant.',
  "Marine snow is a steady fall of organic specks from the sunlit water above. It can take weeks to reach the deep sea floor.",
  'In deep water a wave travels at a speed set by its length alone: a 100 m swell moves at about 12.5 m/s.',
  'Sea state 4, "moderate", means waves from 1.25 to 2.5 m high.',
  'Seawater freezes at about −1.9 °C, colder than fresh water, because of the salt in it.',
  'The SOFAR channel, a layer about 1,000 m down where sound is slowest, can carry low sounds across whole ocean basins.',
  'Giant kelp can grow more than half a metre in a day.',
  'Coral reefs cover well under one percent of the sea floor but are home to about a quarter of all known marine species.',
  'The deepest point of the ocean, the Challenger Deep in the Mariana Trench, is nearly 11,000 m down.',
  "In 1960 Jacques Piccard and Don Walsh reached the bottom of the Challenger Deep in the bathyscaphe Trieste.",
  'In 2012 James Cameron dived alone to the bottom of the Challenger Deep in Deepsea Challenger.',
  "The research submersible Alvin has made more than 5,000 dives since 1964, including to the wreck of Titanic in 1986.",
  'The wreck of Titanic lies about 3,800 m down in the North Atlantic.',
  'The speed of sound in seawater rises with temperature, with salt and with pressure.',
];
